package:
  name: cil-data
  version: 21.3.0

build:
  number: 0  
  noarch: python 

requirements:

  build:
    - python

about:
  home: http://www.ccpi.ac.uk/cil
  license:  Apache 2.0 License
  summary: 'CCPi Core Imaging Library'
